name: Build and Deploy Cucumber Report

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # Lebih stabil dari 24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build and run tests
        run: mvn clean verify

      - name: Upload artifact (manual)
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./target/cucumber-reports

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/cucumber-reports

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
